### ISSUE TITLE
Need to downgrade opencv-python-headless

### ISSUE THREAD

**Issue by bvernay** [tpecot/NucleiSegmentationAndMarkerIDentification#2]
Thank you for this great set of notebooks.
I had to downgrade opencv-python-headless for cellpose to be able to run it

env in python=3.7 (anaconda)
pip3 uninstall opencv-python-headless
pip3 install opencv-python-headless==4.1.2.30
https://stackoverflow.com/questions/70537488/cannot-import-name-registermattype-from-cv2-cv2

Bertrand

**Comment by tpecot** [comment]
Thanks for your help Bertrand !
